name = "email-worker"
main = "./src/index.ts"
compatibility_date = "2024-05-03"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
DISCORD_WEBHOOK_URL = "https://rs.maarifa.org/component/response/api/email/routing"
